# Generated by Django 4.2.7 on 2023-11-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_regist'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='regist',
        ),
    ]
